# Generated by Django 6.0.1 on 2026-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProName', models.CharField(max_length=30)),
                ('ProPrice', models.IntegerField()),
            ],
        ),
    ]
